all:
    # install pycocotools locally
	/home/xsk/anaconda3/bin/python3 setup.py build_ext --inplace
	rm -rf build

install:
	# install pycocotools to the Python site-packages
	/home/xsk/anaconda3/bin/python3 setup.py build_ext install
	rm -rf build